name       : astroid
version    : 0.11.1
release    : 3
source     :
    - https://github.com/astroidmail/astroid/archive/v0.11.1.tar.gz : dcae65cf8dc8a30390da37e5dc0c033ae5733179508999034c1f01d15631ea7c
homepage   : http://astroidmail.github.io/
license    : GPL-3.0-or-later
component  : network.mail
summary    : Lightweight and fast Mail User Agent GUI for notmuch
description: |
    Astroid is a lightweight and fast Mail User Agent that provides a graphical
    interface to searching, displaying and composing email, organized in threads
    and tags. Astroid uses the notmuch backend for blazingly fast searches
    through tons of email. Astroid searches, displays and composes emails - and
    rely on other programs for fetching, syncing and sending email.
builddeps  :
    - pkgconfig(gmime-3.0)
    - pkgconfig(gtkmm-3.0)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(webkitgtk-3.0)
    - pkgconfig(libsass)
    - pkgconfig(libpeas-1.0)
    - pkgconfig(gobject-introspection-1.0)
    - pkgconfig(pygobject-3.0)
    - libboost-devel
    - notmuch-devel
rundeps    :
    - notmuch
setup      : |
    %patch -p1 < $pkgfiles/0001-Revert-464-install-missing-icon-symlinks.patch
    mkdir build && cd build
    %cmake ..
build      : |
    cd build
    %make
install    : |
    cd build
    %make_install
    install -D -d -m 00755 $installdir/usr/share/pixmaps
    ln -s ../astroid/ui/icons/astroid.png $installdir/usr/share/pixmaps/astroid.png
