name       : astroid
version    : '0.13'
release    : 4
source     :
    - https://github.com/astroidmail/astroid/archive/v0.13.tar.gz : 52a5e34b1d8dc597d7fdc9d63d258e519e6d7c3324110de737e5a62906256fb5
homepage   : http://astroidmail.github.io/
license    : GPL-3.0-or-later
component  : network.mail
summary    : Lightweight and fast Mail User Agent GUI for notmuch
description: |
    Astroid is a lightweight and fast Mail User Agent that provides a graphical
    interface to searching, displaying and composing email, organized in threads
    and tags. Astroid uses the notmuch backend for blazingly fast searches
    through tons of email. Astroid searches, displays and composes emails - and
    rely on other programs for fetching, syncing and sending email.
builddeps  :
    - pkgconfig(gmime-3.0)
    - pkgconfig(gobject-introspection-1.0)
    - pkgconfig(gtkmm-3.0)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(libsass)
    - pkgconfig(libpeas-1.0)
    - pkgconfig(protobuf)
    - pkgconfig(pygobject-3.0)
    - pkgconfig(vte-2.91)
    - pkgconfig(webkit2gtk-4.0)
    - libboost-devel
    - notmuch-devel
rundeps    :
    - notmuch
setup      : |
    %cmake
build      : |
    %make
install    : |
    %make_install
    install -d -Dm00755 $installdir/usr/share/pixmaps
    ln -s ../astroid/ui/icons/astroid.png $installdir/usr/share/pixmaps/astroid.png
