name       : astroid
version    : '0.15'
release    : 10
source     :
    - https://github.com/astroidmail/astroid/archive/v0.15.tar.gz : 8581bbdbc71bd00d4cdd473cfad8bc604628bb15616fe5eab5c623461f686c65
homepage   : https://astroidmail.github.io/
license    : GPL-3.0-or-later
component  : network.mail
summary    : Lightweight and fast Mail User Agent GUI for notmuch
description: |
    Astroid is a lightweight and fast Mail User Agent that provides a graphical interface to searching, displaying and composing email, organized in threads and tags. Astroid uses the notmuch backend for blazingly fast searches through tons of email. Astroid searches, displays and composes emails - and rely on other programs for fetching, syncing and sending email.
builddeps  :
    - pkgconfig(gmime-3.0)
    - pkgconfig(gtkmm-3.0)
    - pkgconfig(libsass)
    - pkgconfig(libpeas-1.0)
    - pkgconfig(protobuf)
    - pkgconfig(pygobject-3.0)
    - pkgconfig(scdoc)
    - pkgconfig(vte-2.91)
    - pkgconfig(webkit2gtk-4.0)
    - libboost-devel
    - notmuch-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
    install -dm00644 $installdir/usr/share/pixmaps
    ln -s ../astroid/ui/icons/astroid.png $installdir/usr/share/pixmaps/astroid.png
