name       : astroid
version    : '0.14'
release    : 7
source     :
    - https://github.com/astroidmail/astroid/archive/v0.14.tar.gz : f2642968919527008d383b4c32d4b038c7b6f785ea084dde1222a65162ebc5ca
homepage   : http://astroidmail.github.io/
license    : GPL-3.0-or-later
component  : network.mail
summary    : Lightweight and fast Mail User Agent GUI for notmuch
description: |
    Astroid is a lightweight and fast Mail User Agent that provides a graphical
    interface to searching, displaying and composing email, organized in threads
    and tags. Astroid uses the notmuch backend for blazingly fast searches
    through tons of email. Astroid searches, displays and composes emails - and
    rely on other programs for fetching, syncing and sending email.
builddeps  :
    - pkgconfig(gmime-3.0)
    - pkgconfig(gobject-introspection-1.0)
    - pkgconfig(gtkmm-3.0)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(libsass)
    - pkgconfig(libpeas-1.0)
    - pkgconfig(protobuf)
    - pkgconfig(pygobject-3.0)
    - pkgconfig(vte-2.91)
    - pkgconfig(webkit2gtk-4.0)
    - libboost-devel
    - notmuch-devel
rundeps    :
    - notmuch
setup      : |
    %cmake_ninja -DDISABLE_DOCS=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
    install -d -Dm00755 $installdir/usr/share/pixmaps
    ln -s ../astroid/ui/icons/astroid.png $installdir/usr/share/pixmaps/astroid.png
